# Generated by Django 2.2 on 2020-03-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Сообщение')),
                ('media_attachment', models.CharField(blank=True, help_text='Например для https://vk.com/photo-172443585_456239024 сюда надо вставить photo-172443585_456239024, для видео https://vk.com/video-172443585_456239017 вставить video-172443585_456239017. Все видео должны быть загруженны в бота.', max_length=50, verbose_name='Медиа')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.BooleanField(default=False, help_text='Если установлен то триггер будет срабатывать на вхождение в строку, в противном случае на полное совпадение.')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger', to='botengine.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='RegexTrigger',
            fields=[
                ('trigger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='botengine.Trigger')),
                ('reg_exp', models.TextField()),
            ],
            options={
                'verbose_name': 'РегВыражение триггер',
                'verbose_name_plural': 'РегВыражения триггеры',
            },
            bases=('botengine.trigger',),
        ),
        migrations.CreateModel(
            name='TextTrigger',
            fields=[
                ('trigger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='botengine.Trigger')),
            ],
            options={
                'verbose_name': 'Текстовый триггер',
                'verbose_name_plural': 'Текстовые триггеры',
            },
            bases=('botengine.trigger',),
        ),
        migrations.CreateModel(
            name='OneTextTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('text_trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_text_trigger', to='botengine.TextTrigger')),
            ],
        ),
    ]
